[package]
name = "Tarea04"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.4"
fltk-table = "0.3"
fltk-grid = "0.1"
libc = "0.2"
csv = "1.1"

[[bin]]
name = "set"
path = "src/set_sm.rs"

[[bin]]
name = "del"
path = "src/del_sm.rs"

[[bin]]
name = "app"
path = "src/main.rs"
